
window.YTvideos = [
  { id: 'bryYEtMWCA8', title: 'Chàng Rể Vô Song - Tập 1 - (Chương 1 - 20) | Truyện Ngôn Tình Hay Nhất của Akuradio', time: '100', time_sub: '50' },
  { id: 'nVAAzuJsGrA', title: 'Chàng Rể Vô Song - Tập 2 - (Chương 21 - 40) | Truyện Ngôn Tình Hay Nhất của Akuradio', time: '100', time_sub: '50' },
  { id: 'FIyS5QZb0iI', title: 'Chàng Rể Vô Song - Tập 3 - (Chương 41 - 60) | Truyện Ngôn Tình Hay Nhất của Akuradio', time: '100', time_sub: '50' },
  { id: 'LzwXqwjo0_M', title: 'Chàng Rể Vô Song - Tập 4 - (Chương 61 - 80) | Truyện Ngôn Tình Hay Nhất của Akuradio', time: '100', time_sub: '50' },
  { id: 'J_cZIg665G4', title: 'Chàng Rể Vô Song - Tập 5 - (Chương 81 - 100) | Truyện Ngôn Tình Hay Nhất của Akuradio', time: '100', time_sub: '50' },
  { id: 'fb_imS5U4wE', title: 'Chàng Rể Vô Song - Tập 6 - (Chương 101 - 120) | Truyện Ngôn Tình Hay Nhất của Akuradio', time: '100', time_sub: '50' },
  { id: 'M-sjiJiq364', title: 'Chàng Rể Vô Song - Tập 7 - (Chương 121 - 140) | Truyện Ngôn Tình Hay Nhất của Akuradio', time: '100', time_sub: '50' },
  { id: 'wF9Q1h-I2NA', title: 'Chàng Rể Vô Song - Tập 8 - (Chương 141 - 160) | Truyện Ngôn Tình Hay Nhất của Akuradio', time: '100', time_sub: '50' },
  { id: 'nVAAzuJsGrA', title: 'Chàng Rể Vô Song - Tập 9 - (Chương 161 - 180) | Truyện Ngôn Tình Hay Nhất của Akuradio', time: '100', time_sub: '50' },
  { id: 'bzvw5yboGZE', title: 'Chàng Rể Vô Song - Tập 10 - (Chương 181 - 200) | Truyện Ngôn Tình Hay Nhất của Akuradio', time: '100', time_sub: '50' },
  { id: 'IMKx_heOQfA', title: 'Chàng Rể Vô Song - Tập 11 - (Chương 201 - 220) | Truyện Ngôn Tình Hay Nhất của Akuradio', time: '100', time_sub: '50' },
  { id: 'Zeot9-uUucs', title: 'Chàng Rể Vô Song - Tập 12 - (Chương 221 - 240) | Truyện Ngôn Tình Hay Nhất của Akuradio', time: '100', time_sub: '50' },
  { id: 'KC8nkk5FPGQ', title: '[FULL] Anh Là Của Nợ Của Em |  Truyện ngôn tình ngược - (Siêu Phẩm) của Akuradio', time: '100', time_sub: '50' },
  { id: 'z32CQdQvVdg', title: 'Chồng Phản Bội | tâm sự đau đớn của người vợ khi chồng phản bội + Akuradio', time: '100', time_sub: '50' },
  { id: 'wLdibDT2tTc', title: 'Truyện Mất Rồi Xin Đừng Tìm - Tập 1 | Truyện Ngôn Tình Hay Nhất Năm 2021 của Akuradio', time: '100', time_sub: '50' },
  { id: 'XzOIx-L7Jm4', title: 'Truyện Mất Rồi Xin Đừng Tìm - Tập 2 | Truyện Ngôn Tình Hay Nhất Năm 2021 của Akuradio', time: '100', time_sub: '50' },
  { id: 'u4uSILq26TI', title: 'Truyện Mất Rồi Xin Đừng Tìm - Tập 3 | Truyện Ngôn Tình Hay Nhất Năm 2021 của Akuradio', time: '100', time_sub: '50' },
  { id: 'mIP8kXcMudk', title: 'Truyện Mất Rồi Xin Đừng Tìm - Tập 4 | Truyện Ngôn Tình Hay Nhất Năm 2021 của Akuradio', time: '100', time_sub: '50' },
  { id: 'k2t3z6GQO9w', title: 'Truyện Vợ Anh Là Mẹ Đơn Thân - Tập 1 | Truyện Ngôn Tình của Akuradio', time: '100', time_sub: '50' },
  { id: 'm30REL-B8ds', title: 'Truyện Vợ Anh Là Mẹ Đơn Thân - Tập 2 | Truyện Ngôn Tình của Akuradio', time: '100', time_sub: '50' },
  { id: 'mFy4S6WAtqk', title: 'Truyện Vợ Anh Là Mẹ Đơn Thân - Tập 3 | Truyện Ngôn Tình của Akuradio', time: '100', time_sub: '50' },
  { id: 'zikqVk4XiU8', title: 'Truyện Vợ Anh Là Mẹ Đơn Thân - Tập 4 | Truyện Ngôn Tình của Akuradio', time: '100', time_sub: '50' },
  { id: 'UdEAv9wD3lQ', title: 'Truyện Vợ Anh Là Mẹ Đơn Thân - Tập 5 | Truyện Ngôn Tình của Akuradio', time: '100', time_sub: '50' },
  { id: '-zMZLJqckTY', title: 'Truyện Vợ Anh Là Mẹ Đơn Thân - Tập 6 | Truyện Ngôn Tình của Akuradio', time: '100', time_sub: '50' },
  { id: 'm3kvdrR-3dU', title: 'Mua Mạng Vợ Nhỏ - Tập 1 | Truyện Ngôn Tình của Akuradio', time: '100', time_sub: '50' },
  { id: 'sIZNvq2QdW8', title: 'Mua Mạng Vợ Nhỏ - Tập 2 | Truyện Ngôn Tình của Akuradio', time: '100', time_sub: '50' },
  { id: 'yPstrxy7FLA', title: 'Mua Mạng Vợ Nhỏ - Tập 3 | Truyện Ngôn Tình của Akuradio', time: '100', time_sub: '50' },
  { id: '6AzlINPJlzE', title: 'Mua Mạng Vợ Nhỏ - Tập 4 | Truyện Ngôn Tình của Akuradio', time: '100', time_sub: '50' },
  { id: 'DM0FyhsQOxg', title: 'Mua Mạng Vợ Nhỏ - Tập 5 | Truyện Ngôn Tình của Akuradio', time: '100', time_sub: '50' },
  { id: 'oFSont4gEzI', title: 'Mua Mạng Vợ Nhỏ - Tập 6 | Truyện Ngôn Tình của Akuradio', time: '100', time_sub: '50' },
  { id: 'YMkP_Bzdyqg', title: 'Mua Mạng Vợ Nhỏ - Tập 7 | Truyện Ngôn Tình của Akuradio', time: '100', time_sub: '50' },
  { id: 'Mf4bvqzcHpY', title: 'Mua Mạng Vợ Nhỏ - Tập 8 | Truyện Ngôn Tình của Akuradio', time: '100', time_sub: '50' },
  { id: 'NZLXMzVF2go', title: 'Thần Cấp Ở Rể - Tập 1 - (Chương 1 - 20) | Siêu Phẩm Truyện Ngôn Tình Huyền Huyễn Hay Nhất của Akuradio', time: '100', time_sub: '50' },
  { id: 'HAEHlr_bP1Y', title: 'Thần Cấp Ở Rể - Tập 2 - (Chương 21 - 40) | Siêu Phẩm Truyện Ngôn Tình Huyền Huyễn Hay Nhất của Akuradio', time: '100', time_sub: '50' },
];